# Generated by Django 5.0.6 on 2024-06-28 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='Usuario',
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='anio',
            new_name='Fecha_fabricacion',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='Aceite',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='Color',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='Kilometraje',
        ),
        migrations.AddField(
            model_name='auto',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Usuarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Chequeo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Kilometraje', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Aceite', models.CharField(max_length=100)),
                ('Placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carlist.auto')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
